### PR TITLE
Add missing endpoints to API client

### PR DESCRIPTION
**Pull request by WilfSilver**
Works towards things mentioned in #63 

- Adds the missing endpoints to the API client
- Fixes use of `QueryOptions` instead of `PageOptions`

### CODE REVIEW

**Comment by WilfSilver** [comment]
@Sammy99jsp nudge nudge, I now need this in one of the pages I'm creating

**Comment by Sammy99jsp** [comment]
Yea, I was going to do it after I finish today's allocate Machine Learning time, but I'll attempt to finish now, just for you :)

**Comment by WilfSilver** [comment]
> Yea, I was going to do it after I finish today's allocated Machine Learning time, but I'll attempt to finish now, just for you :)

It's fine, I have just put a placeholder for now, so feel free to focus on ML

**Review by Sammy99jsp — APPROVED** [review]
Good job, you reliable robin 🐦!

**Pull request merged**
