### PR TITLE
Add ability to rate a user after a match

### PR DESCRIPTION
**Pull request by WilfSilver**
### Summary

Allows a user to rate another once they have completed a match together

- A user can only rate another user 1 per match
- Stores ratings as a number for each of the possible stars (1, 2, 3, 4, 5) which the frontend can then workout the average.

### TODO

- [x] Add testing for the rating endpoint
- [x] Update existing tests to include the new ratings object

### Testing

Unit tests have been added

### CODE REVIEW

**Comment by WilfSilver** [comment]
This is also blocked on #69 and #66

**Review by castellacodes — APPROVED** [review]
All good to me :)

**Review by Sammy99jsp — APPROVED** [review]
LGTM! Loooong tests be like,

**Comment by Sammy99jsp** [comment]
Oh wait @WilfSilver there are merge conflicts lol.

**Pull request merged**
