### PR TITLE
Single League Page + Other stuff.

### PR DESCRIPTION
**Pull request by Sammy99jsp**
* Single League Page.
  * New endpoint: `/league/:id/rounds` to return the number of rounds the league has.
* Nicer loading animation.
* New `Feed` component, for partitioning items from an async feed.

### CODE REVIEW

**Comment by Sammy99jsp** [comment]
image
He rolls :)

**Comment by Sammy99jsp** [comment]
Feeds can now be divided into sections declaratively, by returning a `Record<section, Item[]>` instead of `Item[]` (but it is still backwards-compatible with the previous `CardList` interface):
image
Result
image

**Comment by Sammy99jsp** [comment]
@WilfSilver actually I'm gonna draft this again: Your PRs will cause merge conflicts.

**Review by WilfSilver — APPROVED** [review]
LGTM

**Pull request merged**
